# Generated by Django 4.1 on 2023-10-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extract", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinputpost",
            name="patient_id",
        ),
        migrations.RemoveField(
            model_name="userinputpost",
            name="patient_name",
        ),
        migrations.AddField(
            model_name="userinputpost",
            name="patient_records",
            field=models.FileField(default=None, upload_to="documents/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinputpost",
            name="prompt_info",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
